---
title: "ML_bulk"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Libraries and data
```{r}
rm(list=ls())
set.seed(123)
# Load the libraries
library("tidyverse")
library("xtable")
library(janitor)
library(cluster)
library(factoextra)
library(data.table)

# Read the data 
bulk_counts <- read.csv("/home/people/felpas/CoDA_scRNAseq/data/bulk/counts_bulk_patient.tsv", sep = "\t")
deseq_counts <- read.csv(unz("/home/people/felpas/CoDA_scRNAseq/results/bulk/deseq2_DE.csv.zip","deseq2_DE.csv"))
edge_counts <- read.csv(unz("/home/people/felpas/CoDA_scRNAseq/results/bulk/edgeR_DE.csv.zip", "edgeR_DE.csv"))
aldex_counts <- read.csv(unz("/home/people/felpas/CoDA_scRNAseq/results/bulk/aldex2_clr.csv.zip", "aldex2_clr.csv"))
clr_counts = fread("/home/people/felpas/CoDA_scRNAseq/results/bulk/clr_counts.csv.gz")
```

## Wrangle counts on different inputs

```{r, echo=FALSE}
# Clean bulk counts by erasing all 0 columns
bulk_counts[63152,"Ensembl_gene_id"] <-"TC_"
bulk_counts <- bulk_counts[-c(63152), ] 
bulk_counts<- bulk_counts[apply(bulk_counts[,-1], 1, function(x) !all(x==0)),]


# Remove non-relevant columns for the ML algorithms
deseq_counts <- subset(deseq_counts, select = -c(baseMean,log2FoldChange,lfcSE, stat,pvalue,padj))
edge_counts <- subset(edge_counts, select = -c(logCPM,PValue,dispersion, logFC,LR,FDR))

# Transpose counts matrix

bulk_counts_t = as.data.frame(t(as.matrix(bulk_counts)))
bulk_counts_t <- row_to_names(bulk_counts_t, row_number = 1)


deseq_counts_t = as.data.frame(t(as.matrix(deseq_counts)))
deseq_counts_t <- row_to_names(deseq_counts_t, row_number = 1)


edge_counts_t = as.data.frame(t(as.matrix(edge_counts)))
edge_counts_t <- row_to_names(edge_counts_t, row_number = 1)


aldex_counts_t = as.data.frame(t(as.matrix(aldex_counts)))
aldex_counts_t <- row_to_names(aldex_counts_t, row_number = 1)

# Transpose counts matrix

clr_counts_t = as.data.frame(t(as.matrix(clr_counts)))
clr_counts_t <- clean_names(row_to_names(bulk_counts_t, row_number = 1))
```

## K-means clustering

```{r, echo=FALSE}
### ---------- RAW DATA -----------

# Compute k-means
res_means_raw = kmeans(bulk_counts_t, centers = 2, nstart = 20)

# Process output
res_viz_raw <- as.data.frame(res_means_raw$cluster)
names(res_viz_raw)[1] <- "cluster"
res_viz_raw <- cbind(sample_name = rownames(res_viz_raw), res_viz_raw)
rownames(res_viz_raw) <- 1:nrow(res_viz_raw)

library(stringr)
res_viz_raw$phenotype <- str_sub(res_viz_raw$sample_name, 5)
res_viz_raw$phenotype <- str_sub(res_viz_raw$phenotype, start=1,end=1)

correct_clustering_T =  res_viz_raw[res_viz_raw$cluster==1 & res_viz_raw$phenotype =="T", ]
correct_clustering_N =  res_viz_raw[res_viz_raw$cluster==2 & res_viz_raw$phenotype =="N", ]
accuracy_raw = (nrow(correct_clustering_T)+nrow(correct_clustering_N)) / nrow(res_viz_raw)


### ---------- DESeq2 normalized data -----------
# Compute k-means
res_means_deseq = kmeans(deseq_counts_t, centers = 2, nstart = 20)

# Process output
res_viz_deseq <- as.data.frame(res_means_deseq$cluster)
names(res_viz_deseq)[1] <- "cluster"
res_viz_deseq <- cbind(sample_name = rownames(res_viz_deseq), res_viz_deseq)
rownames(res_viz_deseq) <- 1:nrow(res_viz_deseq)

library(stringr)
res_viz_deseq$phenotype <- str_sub(res_viz_deseq$sample_name, 5)
res_viz_deseq$phenotype <- str_sub(res_viz_deseq$phenotype, start=1,end=1)

correct_clustering_T =  res_viz_deseq[res_viz_deseq$cluster==1 & res_viz_deseq$phenotype =="T", ]
correct_clustering_N =  res_viz_deseq[res_viz_deseq$cluster==2 & res_viz_deseq$phenotype =="N", ]
accuracy_deseq = (nrow(correct_clustering_T)+nrow(correct_clustering_N)) / nrow(res_viz_deseq)



### ---------- edgeR DATA -----------
# Compute k-means
res_means_edge = kmeans(edge_counts_t, centers = 2, nstart = 20)

# Process output
res_viz_edge <- as.data.frame(res_means_edge$cluster)
names(res_viz_edge)[1] <- "cluster"
res_viz_edge <- cbind(sample_name = rownames(res_viz_edge), res_viz_edge)
rownames(res_viz_edge) <- 1:nrow(res_viz_edge)

library(stringr)
res_viz_edge$phenotype <- str_sub(res_viz_edge$sample_name, 5)
res_viz_edge$phenotype <- str_sub(res_viz_edge$phenotype, start=1,end=1)

correct_clustering_T =  res_viz_edge[res_viz_edge$cluster==1 & res_viz_edge$phenotype =="T", ]
correct_clustering_N =  res_viz_edge[res_viz_edge$cluster==2 & res_viz_edge$phenotype =="N", ]
accuracy_edge = (nrow(correct_clustering_T)+nrow(correct_clustering_N)) / nrow(res_viz_edge)



### ---------- ALDEx2 DATA -----------
# Compute k-means
res_means_aldex = kmeans(aldex_counts_t, centers = 2, nstart = 20)

# Process output
res_viz_aldex <- as.data.frame(res_means_aldex$cluster)
names(res_viz_aldex)[1] <- "cluster"
res_viz_aldex <- cbind(sample_name = rownames(res_viz_aldex), res_viz_aldex)
rownames(res_viz_aldex) <- 1:nrow(res_viz_aldex)

library(stringr)
res_viz_aldex$phenotype <- str_sub(res_viz_aldex$sample_name, 5)
res_viz_aldex$phenotype <- str_sub(res_viz_aldex$phenotype, start=1,end=1)

correct_clustering_T =  res_viz_aldex[res_viz_aldex$cluster==1 & res_viz_aldex$phenotype =="T", ]
correct_clustering_N =  res_viz_aldex[res_viz_aldex$cluster==2 & res_viz_aldex$phenotype =="N", ]
accuracy_aldex = (nrow(correct_clustering_T)+nrow(correct_clustering_N)) / nrow(res_viz_aldex)

### ---------- CLR DATA -----------

# Compute k-means
res_means_clr = kmeans(clr_counts_t, centers = 2, nstart = 20)

# Process output
res_viz_clr <- as.data.frame(res_means_clr$cluster)
names(res_viz_clr)[1] <- "cluster"
res_viz_clr <- cbind(sample_name = rownames(res_viz_clr), res_viz_clr)
rownames(res_viz_clr) <- 1:nrow(res_viz_clr)

library(stringr)
res_viz_clr$phenotype <- str_sub(res_viz_clr$sample_name, 5)
res_viz_clr$phenotype <- str_sub(res_viz_clr$phenotype, start=1,end=1)

correct_clustering_T =  res_viz_clr[res_viz_clr$cluster==1 & res_viz_clr$phenotype =="T", ]
correct_clustering_N =  res_viz_clr[res_viz_clr$cluster==2 & res_viz_clr$phenotype =="N", ]
accuracy_clr = (nrow(correct_clustering_T)+nrow(correct_clustering_N)) / nrow(res_viz_clr)


r1T <- nrow(res_viz_raw[res_viz_raw$cluster==1 & res_viz_raw$phenotype=="T",])/nrow(res_viz_raw[res_viz_raw$cluster==1,]) 
r1N <- nrow(res_viz_raw[res_viz_raw$cluster==1 & res_viz_raw$phenotype=="N",])/nrow(res_viz_raw[res_viz_raw$cluster==1,]) 
r2N <- nrow(res_viz_raw[res_viz_raw$cluster==2 & res_viz_raw$phenotype=="N",])/nrow(res_viz_raw[res_viz_raw$cluster==2,]) 
r2T <- nrow(res_viz_raw[res_viz_raw$cluster==2 & res_viz_raw$phenotype=="T",])/nrow(res_viz_raw[res_viz_raw$cluster==2,]) 

d1T <- nrow(res_viz_deseq[res_viz_deseq$cluster==1 & res_viz_deseq$phenotype=="T",])/nrow(res_viz_deseq[res_viz_deseq$cluster==1,]) 
d1N <- nrow(res_viz_deseq[res_viz_deseq$cluster==1 & res_viz_deseq$phenotype=="N",])/nrow(res_viz_deseq[res_viz_deseq$cluster==1,]) 
d2N <- nrow(res_viz_deseq[res_viz_deseq$cluster==2 & res_viz_deseq$phenotype=="N",])/nrow(res_viz_deseq[res_viz_deseq$cluster==2,]) 
d2T <- nrow(res_viz_deseq[res_viz_deseq$cluster==2 & res_viz_deseq$phenotype=="T",])/nrow(res_viz_deseq[res_viz_deseq$cluster==2,]) 

e1T <- nrow(res_viz_edge[res_viz_edge$cluster==1 & res_viz_edge$phenotype=="T",])/nrow(res_viz_edge[res_viz_edge$cluster==1,])
e1N <- nrow(res_viz_edge[res_viz_edge$cluster==1 & res_viz_edge$phenotype=="N",])/nrow(res_viz_edge[res_viz_edge$cluster==1,]) 
e2N <- nrow(res_viz_edge[res_viz_edge$cluster==2 & res_viz_edge$phenotype=="N",])/nrow(res_viz_edge[res_viz_edge$cluster==2,]) 
e2T <- nrow(res_viz_edge[res_viz_edge$cluster==2 & res_viz_edge$phenotype=="T",])/nrow(res_viz_edge[res_viz_edge$cluster==2,]) 

a1T <- nrow(res_viz_aldex[res_viz_aldex$cluster==1 & res_viz_aldex$phenotype=="T",])/nrow(res_viz_aldex[res_viz_aldex$cluster==1,]) 
a1N <- nrow(res_viz_aldex[res_viz_aldex$cluster==1 & res_viz_aldex$phenotype=="N",])/nrow(res_viz_aldex[res_viz_aldex$cluster==1,]) 
a2N <- nrow(res_viz_aldex[res_viz_aldex$cluster==2 & res_viz_aldex$phenotype=="N",])/nrow(res_viz_aldex[res_viz_aldex$cluster==2,]) 
a2T <- nrow(res_viz_aldex[res_viz_aldex$cluster==2 & res_viz_aldex$phenotype=="T",])/nrow(res_viz_aldex[res_viz_aldex$cluster==2,]) 


c1T <- nrow(res_viz_clr[res_viz_clr$cluster==1 & res_viz_clr$phenotype=="T",])/nrow(res_viz_clr[res_viz_clr$cluster==1,]) 
c1N <- nrow(res_viz_clr[res_viz_clr$cluster==1 & res_viz_clr$phenotype=="N",])/nrow(res_viz_clr[res_viz_clr$cluster==1,]) 
c2N <- nrow(res_viz_clr[res_viz_clr$cluster==2 & res_viz_clr$phenotype=="N",])/nrow(res_viz_clr[res_viz_clr$cluster==2,]) 
c2T <- nrow(res_viz_clr[res_viz_clr$cluster==2 & res_viz_clr$phenotype=="T",])/nrow(res_viz_clr[res_viz_clr$cluster==2,]) 

if (r1T>r1N) {
cat("Raw data -- Cluster purity:\n\tCluster 1:")
cat(r1T)
cat("\n\tCluster 2:")
cat(r2N)
cat("\n")
} else {
cat("Cluster purity:\n\tCluster 1:")
cat(r1N)
cat("\n\tCluster 2:")
cat(r2T)
cat("\n")
}

if (d1T>d1N) {
cat("DESeq2 data -- Cluster purity:\n\tCluster 1:")
cat(d1T)
cat("\n\tCluster 2:")
cat(d2N)
cat("\n")
} else {
cat("DESeq2 data -- Cluster purity:\n\tCluster 1:")
cat(d1N)
cat("\n\tCluster 2:")
cat(d2T)
cat("\n")
}

if (e1T>e1N) {
cat("EdgeR data -- Cluster purity:\n\tCluster 1:")
cat(e1T)
cat("\n\tCluster 2:")
cat(e2N)
cat("\n")
} else {
cat("EdgeR data -- Cluster purity:\n\tCluster 1:")
cat(e1N)
cat("\n\tCluster 2:")
cat(e2T)
cat("\n")
}

if (a1T>a1N) {
cat("ALDEx2 data -- Cluster purity:\n\tCluster 1:")
cat(a1T)
cat("\n\tCluster 2:")
cat(a2N)
} else {
cat("ALDEx2 data -- Cluster purity:\n\tCluster 1:")
cat(a1N)
cat("\n\tCluster 2:")
cat(a2T)
}

if (c1T>c1N) {
cat("CLR data -- Cluster purity:\n\tCluster 1:")
cat(c1T)
cat("\n\tCluster 2:")
cat(c2N)
} else {
cat("CLR data -- Cluster purity:\n\tCluster 1:")
cat(c1N)
cat("\n\tCluster 2:")
cat(c2T)
}
```

## Visualize results for K-means clustering 
```{r, echo=FALSE}
# PCA 
#rownames(bulk_counts) <- bulk_counts[,1]
#bulk_counts$Ensembl_gene_id <- NULL
bulk_countss <- as.data.frame(lapply(bulk_counts_t, as.numeric))
res.pca <- prcomp(bulk_countss, scale = FALSE)

df_pca <- as.data.frame(res.pca[["x"]])
labels <- row.names(bulk_counts_t)
df_pca$labels <- labels
df_pca$phenotype <- str_sub(df_pca$labels, start = 5, end = 5)

# Dimension reduction using PCA
res.pca <- prcomp(bulk_countss, scale = FALSE)
# Coordinates of individuals
ind.coord <- as.data.frame(get_pca_ind(res.pca)$coord)
# Add clusters obtained using the K-means algorithm
ind.coord$cluster <- factor(res_means_raw$cluster)
# Add Species groups from the original data sett
ind.coord$label <- df_pca$phenotype
# Data inspection
head(ind.coord)

# Percentage of variance explained by dimensions
eigenvalue <- round(get_eigenvalue(res.pca), 1)
variance.percent <- eigenvalue$variance.percent
head(eigenvalue)

library(ggpubr)

ggscatter(
  ind.coord, x = "Dim.1", y = "Dim.2", title="raw data clustering (k=2)",
  color = "cluster", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "label", size = 1.5,  legend = "right", ggtheme = theme_bw(),
  xlab = paste0("Dim 1 (", variance.percent[1], "% )" ),
  ylab = paste0("Dim 2 (", variance.percent[2], "% )" )
) +
  stat_mean(aes(color = cluster), size = 4)

# Raw 3 clusters

# Compute k-means
res_means_raw = kmeans(bulk_counts_t, centers = 3, nstart = 20)

# Process output
res_viz_raw <- as.data.frame(res_means_raw$cluster)
names(res_viz_raw)[1] <- "cluster"
res_viz_raw <- cbind(sample_name = rownames(res_viz_raw), res_viz_raw)
rownames(res_viz_raw) <- 1:nrow(res_viz_raw)

bulk_countss <- as.data.frame(lapply(bulk_counts_t, as.numeric))
res.pca <- prcomp(bulk_countss, scale = FALSE)

df_pca <- as.data.frame(res.pca[["x"]])
labels <- row.names(bulk_counts_t)
df_pca$labels <- labels
df_pca$phenotype <- str_sub(df_pca$labels, start = 5, end = 5)

# Dimension reduction using PCA
res.pca <- prcomp(bulk_countss, scale = FALSE)
# Coordinates of individuals
ind.coord <- as.data.frame(get_pca_ind(res.pca)$coord)
# Add clusters obtained using the K-means algorithm
ind.coord$cluster <- factor(res_means_raw$cluster)
# Add Species groups from the original data sett
ind.coord$label <- df_pca$phenotype
# Data inspection
head(ind.coord)

# Percentage of variance explained by dimensions
eigenvalue <- round(get_eigenvalue(res.pca), 1)
variance.percent <- eigenvalue$variance.percent
head(eigenvalue)

library(ggpubr)

ggscatter(
  ind.coord, x = "Dim.1", y = "Dim.2", title="raw data clustering (k=3)",
  color = "cluster", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "label", size = 1.5,  legend = "right", ggtheme = theme_bw(),
  xlab = paste0("Dim 1 (", variance.percent[1], "% )" ),
  ylab = paste0("Dim 2 (", variance.percent[2], "% )" )
) +
  stat_mean(aes(color = cluster), size = 4)


##---------- DESeq2 -----------

deseq_countss <- as.data.frame(lapply(deseq_counts_t, as.numeric))
res.pca_deseq <- prcomp(deseq_countss, scale = FALSE)

df_pca_deseq <- as.data.frame(res.pca_deseq[["x"]])
labels <- row.names(deseq_counts_t)
df_pca_deseq$labels <- labels
df_pca_deseq$phenotype <- str_sub(df_pca_deseq$labels, start = 5, end = 5)

# Dimension reduction using PCA
res.pca_deseq <- prcomp(deseq_countss, scale = FALSE)
# Coordinates of individuals
ind.coord <- as.data.frame(get_pca_ind(res.pca_deseq)$coord)
# Add clusters obtained using the K-means algorithm
ind.coord$cluster <- factor(res_means_deseq$cluster)
# Add Species groups from the original data sett
ind.coord$label <- df_pca_deseq$phenotype
# Data inspection
head(ind.coord)

# Percentage of variance explained by dimensions
eigenvalue <- round(get_eigenvalue(res.pca_deseq), 1)
variance.percent <- eigenvalue$variance.percent
head(eigenvalue)

ggscatter(
  ind.coord, x = "Dim.1", y = "Dim.2", title = "DESeq2 data clustering (k=2)",
  color = "cluster", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "label", size = 1.5,  legend = "right", ggtheme = theme_bw(),
  xlab = paste0("Dim 1 (", variance.percent[1], "% )" ),
  ylab = paste0("Dim 2 (", variance.percent[2], "% )" )
) +
  stat_mean(aes(color = cluster), size = 4)
# DESeq2 with 3 clusters
# Compute k-means
res_means_deseq = kmeans(deseq_counts_t, centers = 3, nstart = 20)

# Process output
res_viz_deseq <- as.data.frame(res_means_deseq$cluster)
names(res_viz_deseq)[1] <- "cluster"
res_viz_deseq <- cbind(sample_name = rownames(res_viz_deseq), res_viz_deseq)
rownames(res_viz_deseq) <- 1:nrow(res_viz_deseq)

deseq_countss <- as.data.frame(lapply(deseq_counts_t, as.numeric))
res.pca_deseq <- prcomp(deseq_countss, scale = FALSE)

df_pca_deseq <- as.data.frame(res.pca_deseq[["x"]])
labels <- row.names(deseq_counts_t)
df_pca_deseq$labels <- labels
df_pca_deseq$phenotype <- str_sub(df_pca_deseq$labels, start = 5, end = 5)

# Dimension reduction using PCA
res.pca_deseq <- prcomp(deseq_countss, scale = FALSE)
# Coordinates of individuals
ind.coord <- as.data.frame(get_pca_ind(res.pca_deseq)$coord)
# Add clusters obtained using the K-means algorithm
ind.coord$cluster <- factor(res_means_deseq$cluster)
# Add Species groups from the original data sett
ind.coord$label <- df_pca_deseq$phenotype
# Data inspection
head(ind.coord)

# Percentage of variance explained by dimensions
eigenvalue <- round(get_eigenvalue(res.pca_deseq), 1)
variance.percent <- eigenvalue$variance.percent
head(eigenvalue)

ggscatter(
  ind.coord, x = "Dim.1", y = "Dim.2", title = "DESeq2 data clustering (k=3)",
  color = "cluster", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "label", size = 1.5,  legend = "right", ggtheme = theme_bw(),
  xlab = paste0("Dim 1 (", variance.percent[1], "% )" ),
  ylab = paste0("Dim 2 (", variance.percent[2], "% )" )
) +
  stat_mean(aes(color = cluster), size = 4)

##---------- edgeR-----------

edge_countss <- as.data.frame(lapply(edge_counts_t, as.numeric))
res.pca_edge <- prcomp(edge_countss, scale = FALSE)

df_pca_edge <- as.data.frame(res.pca_edge[["x"]])
labels <- row.names(edge_counts_t)
df_pca_edge$labels <- labels
df_pca_edge$phenotype <- str_sub(df_pca_edge$labels, start = 5, end = 5)

# Dimension reduction using PCA
res.pca_edge <- prcomp(edge_countss, scale = FALSE)
# Coordinates of individuals
ind.coord <- as.data.frame(get_pca_ind(res.pca_edge)$coord)
# Add clusters obtained using the K-means algorithm
ind.coord$cluster <- factor(res_means_edge$cluster)
# Add Species groups from the original data sett
ind.coord$label <- df_pca_edge$phenotype
# Data inspection
head(ind.coord)

# Percentage of variance explained by dimensions
eigenvalue <- round(get_eigenvalue(res.pca_edge), 1)
variance.percent <- eigenvalue$variance.percent
head(eigenvalue)

ggscatter(
  ind.coord, x = "Dim.1", y = "Dim.2", title = "EdgeR data clustering (k=2)",
  color = "cluster", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "label", size = 1.5,  legend = "right", ggtheme = theme_bw(),
  xlab = paste0("Dim 1 (", variance.percent[1], "% )" ),
  ylab = paste0("Dim 2 (", variance.percent[2], "% )" )
) +
  stat_mean(aes(color = cluster), size = 4)

# Edge3 with 3 clusters 
# Compute k-means
res_means_edge = kmeans(edge_counts_t, centers = 3, nstart = 20)

# Process output
res_viz_edge <- as.data.frame(res_means_edge$cluster)
names(res_viz_edge)[1] <- "cluster"
res_viz_edge <- cbind(sample_name = rownames(res_viz_edge), res_viz_edge)
rownames(res_viz_edge) <- 1:nrow(res_viz_edge)

edge_countss <- as.data.frame(lapply(edge_counts_t, as.numeric))
res.pca_edge <- prcomp(edge_countss, scale = FALSE)

df_pca_edge <- as.data.frame(res.pca_edge[["x"]])
labels <- row.names(edge_counts_t)
df_pca_edge$labels <- labels
df_pca_edge$phenotype <- str_sub(df_pca_edge$labels, start = 5, end = 5)

# Dimension reduction using PCA
res.pca_edge <- prcomp(edge_countss, scale = FALSE)
# Coordinates of individuals
ind.coord <- as.data.frame(get_pca_ind(res.pca_edge)$coord)
# Add clusters obtained using the K-means algorithm
ind.coord$cluster <- factor(res_means_edge$cluster)
# Add Species groups from the original data sett
ind.coord$label <- df_pca_edge$phenotype
# Data inspection
head(ind.coord)

# Percentage of variance explained by dimensions
eigenvalue <- round(get_eigenvalue(res.pca_edge), 1)
variance.percent <- eigenvalue$variance.percent
head(eigenvalue)

ggscatter(
  ind.coord, x = "Dim.1", y = "Dim.2", title = "EdgeR data clustering (k=3)",
  color = "cluster", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "label", size = 1.5,  legend = "right", ggtheme = theme_bw(),
  xlab = paste0("Dim 1 (", variance.percent[1], "% )" ),
  ylab = paste0("Dim 2 (", variance.percent[2], "% )" )
) +
  stat_mean(aes(color = cluster), size = 4)

##---------- ALDEx2-----------

aldex_countss <- as.data.frame(lapply(aldex_counts_t, as.numeric))
res.pca_aldex <- prcomp(aldex_countss, scale = FALSE)

df_pca_aldex <- as.data.frame(res.pca_aldex[["x"]])
labels <- row.names(aldex_counts_t)
df_pca_aldex$labels <- labels
df_pca_aldex$phenotype <- str_sub(df_pca_aldex$labels, start = 5, end = 5)

# Dimension reduction using PCA
res.pca_aldex <- prcomp(aldex_countss, scale = FALSE)
# Coordinates of individuals
ind.coord <- as.data.frame(get_pca_ind(res.pca_aldex)$coord)
# Add clusters obtained using the K-means algorithm
ind.coord$cluster <- factor(res_means_aldex$cluster)
# Add Species groups from the original data sett
ind.coord$label <- df_pca_aldex$phenotype
# Data inspection
head(ind.coord)

# Percentage of variance explained by dimensions
eigenvalue <- round(get_eigenvalue(res.pca_aldex), 1)
variance.percent <- eigenvalue$variance.percent
head(eigenvalue)

ggscatter(
  ind.coord, x = "Dim.1", y = "Dim.2", title = "ALDEx2 data clustering (k=2)",
  color = "cluster", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "label", size = 1.5,  legend = "right", ggtheme = theme_bw(),
  xlab = paste0("Dim 1 (", variance.percent[1], "% )" ),
  ylab = paste0("Dim 2 (", variance.percent[2], "% )" )
) +
  stat_mean(aes(color = cluster), size = 4)

# ALDEX2 with 3 k means
# Compute k-means
res_means_aldex = kmeans(aldex_counts_t, centers = 3, nstart = 20)

# Process output
res_viz_aldex <- as.data.frame(res_means_aldex$cluster)
names(res_viz_aldex)[1] <- "cluster"
res_viz_aldex <- cbind(sample_name = rownames(res_viz_aldex), res_viz_aldex)
rownames(res_viz_aldex) <- 1:nrow(res_viz_aldex)

aldex_countss <- as.data.frame(lapply(aldex_counts_t, as.numeric))
res.pca_aldex <- prcomp(aldex_countss, scale = FALSE)

df_pca_aldex <- as.data.frame(res.pca_aldex[["x"]])
labels <- row.names(aldex_counts_t)
df_pca_aldex$labels <- labels
df_pca_aldex$phenotype <- str_sub(df_pca_aldex$labels, start = 5, end = 5)

# Dimension reduction using PCA
res.pca_aldex <- prcomp(aldex_countss, scale = FALSE)
# Coordinates of individuals
ind.coord <- as.data.frame(get_pca_ind(res.pca_aldex)$coord)
# Add clusters obtained using the K-means algorithm
ind.coord$cluster <- factor(res_means_aldex$cluster)
# Add Species groups from the original data sett
ind.coord$label <- df_pca_aldex$phenotype
# Data inspection
head(ind.coord)

# Percentage of variance explained by dimensions
eigenvalue <- round(get_eigenvalue(res.pca_aldex), 1)
variance.percent <- eigenvalue$variance.percent
head(eigenvalue)

ggscatter(
  ind.coord, x = "Dim.1", y = "Dim.2", title = "ALDEx2 data clustering (k=3)",
  color = "cluster", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "label", size = 1.5,  legend = "right", ggtheme = theme_bw(),
  xlab = paste0("Dim 1 (", variance.percent[1], "% )" ),
  ylab = paste0("Dim 2 (", variance.percent[2], "% )" )
) +
  stat_mean(aes(color = cluster), size = 4)


##---------- CLR -----------

clr_countss <- as.data.frame(lapply(clr_counts_t, as.numeric))
res.pca_clr <- prcomp(clr_countss, scale = FALSE)

df_pca_clr <- as.data.frame(res.pca_clr[["x"]])
labels <- row.names(clr_counts_t)
df_pca_clr$labels <- labels
df_pca_clr$phenotype <- str_sub(df_pca_clr$labels, start = 5, end = 5)

# Dimension reduction using PCA
res.pca_clr <- prcomp(clr_countss, scale = FALSE)
# Coordinates of individuals
ind.coord <- as.data.frame(get_pca_ind(res.pca_clr)$coord)
# Add clusters obtained using the K-means algorithm
ind.coord$cluster <- factor(res_means_clr$cluster)
# Add Species groups from the original data sett
ind.coord$label <- df_pca_clr$phenotype
# Data inspection
head(ind.coord)

# Percentage of variance explained by dimensions
eigenvalue <- round(get_eigenvalue(res.pca_clr), 1)
variance.percent <- eigenvalue$variance.percent
head(eigenvalue)

ggscatter(
  ind.coord, x = "Dim.1", y = "Dim.2", title = "CLR data clustering (k=2)",
  color = "cluster", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "label", size = 1.5,  legend = "right", ggtheme = theme_bw(),
  xlab = paste0("Dim 1 (", variance.percent[1], "% )" ),
  ylab = paste0("Dim 2 (", variance.percent[2], "% )" )
) +
  stat_mean(aes(color = cluster), size = 4)


```

## KNN algorithm

```{r}
## KNN algorithm

# RAW DATA
set.seed(1996)
ran <- sample(1:nrow(bulk_counts_t), 0.9 * nrow(bulk_counts_t)) 
 
##extract training set
#bulk_counts <- bulk_counts_t[,!names(bulk_counts_t) %in% "Ensembl_gene_id"]
bulk_counts_train <- bulk_counts_t[ran,] 

##extract testing set
bulk_counts_test <- bulk_counts_t[-ran,] 

## extract labels
targets_train<- str_sub(rownames(bulk_counts_t), start=5,end=5)[ran]
targets_test <-  str_sub(rownames(bulk_counts_t), start=5,end=5)[-ran]
# Compute KNN function
library(class)

accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}

k_to_try = 1:35
err_k_raw = rep(x = 0, times = length(k_to_try))

for (i in seq_along(k_to_try)) {
  pred = knn(train = bulk_counts_train, 
             test  = bulk_counts_test, 
             cl    = targets_train, 
             k     = k_to_try[i])
  tab = table(pred, targets_test)
  err_k_raw[i] <- accuracy(tab)
}

# DESeq2 DATA
ran <- sample(1:nrow(deseq_counts_t), 0.9 * nrow(deseq_counts_t)) 
 
##extract training set
#deseq_counts <- deseq_counts[,!names(deseq_counts) %in% "X"]
deseq_counts_train <- deseq_counts_t[ran,] 

##extract testing set
deseq_counts_test <- deseq_counts_t[-ran,] 

## extract labels
targets_train<- str_sub(rownames(deseq_counts_t), start=5,end=5)[ran]
targets_test <-  str_sub(rownames(deseq_counts_t), start=5,end=5)[-ran]
# Compute KNN function
library(class)

accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}

k_to_try = 1:35
err_k_deseq = rep(x = 0, times = length(k_to_try))

for (i in seq_along(k_to_try)) {
  pred = knn(train = deseq_counts_train, 
             test  = deseq_counts_test, 
             cl    = targets_train, 
             k     = k_to_try[i])
  tab = table(pred, targets_test)
  err_k_deseq[i] <- accuracy(tab)
}

# EdgeR
ran <- sample(1:nrow(edge_counts_t), 0.9 * nrow(edge_counts_t)) 
 
##extract training set
edge_counts <- edge_counts_t[,!names(edge_counts_t) %in% "X"]
edge_counts_train <- edge_counts_t[ran,] 

##extract testing set
edge_counts_test <- edge_counts_t[-ran,] 

## extract labels
targets_train<- str_sub(rownames(edge_counts_t), start=5,end=5)[ran]
targets_test <-  str_sub(rownames(edge_counts_t), start=5,end=5)[-ran]
# Compute KNN function
library(class)

accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}

k_to_try = 1:35
err_k_edge = rep(x = 0, times = length(k_to_try))

for (i in seq_along(k_to_try)) {
  pred = knn(train = edge_counts_train, 
             test  = edge_counts_test, 
             cl    = targets_train, 
             k     = k_to_try[i])
  tab = table(pred, targets_test)
  err_k_edge[i] <- accuracy(tab)
}


# ALDEx2
ran <- sample(1:nrow(aldex_counts_t), 0.9 * nrow(aldex_counts_t)) 
 
##extract training set
aldex_counts <- aldex_counts_t[,!names(aldex_counts_t) %in% "X"]
aldex_counts_train <- aldex_counts_t[ran,] 

##extract testing set
aldex_counts_test <- aldex_counts_t[-ran,] 

## extract labels
targets_train<- str_sub(rownames(aldex_counts_t), start=5,end=5)[ran]
targets_test <-  str_sub(rownames(aldex_counts_t), start=5,end=5)[-ran]

# Compute KNN function
library(class)

accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}

k_to_try = 1:35
err_k_aldex = rep(x = 0, times = length(k_to_try))

for (i in seq_along(k_to_try)) {
  pred = knn(train = aldex_counts_train, 
             test  = aldex_counts_test, 
             cl    = targets_train, 
             k     = k_to_try[i])
  tab = table(pred, targets_test)
  err_k_aldex[i] <- accuracy(tab)
}

# CLR
ran <- sample(1:nrow(clr_counts_t), 0.9 * nrow(clr_counts_t)) 
 
##extract training set
clr_counts <- clr_counts_t[,!names(clr_counts_t) %in% "X"]
clr_counts_train <- clr_counts_t[ran,] 

##extract testing set
clr_counts_test <- clr_counts_t[-ran,] 

## extract labels
targets_train<- str_sub(rownames(clr_counts_t), start=5,end=5)[ran]
targets_test <-  str_sub(rownames(clr_counts_t), start=5,end=5)[-ran]
# Compute KNN function
library(class)

accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}

k_to_try = 1:35
err_k_clr = rep(x = 0, times = length(k_to_try))

for (i in seq_along(k_to_try)) {
  pred = knn(train = clr_counts_train, 
             test  = clr_counts_test, 
             cl    = targets_train, 
             k     = k_to_try[i])
  tab = table(pred, targets_test)
  err_k_clr[i] <- accuracy(tab)
}


plot(err_k_raw, type = "b", col = "darkolivegreen4",
     lty = 1, xlab = "k, number of neighbors", ylab = "Accuracy",
     main = "Accuracy with k-neighbors",ylim=c(60,103))


lines(k_to_try, err_k_deseq, type = "b", lty = 1, col='firebrick1')
lines(k_to_try, err_k_edge, type = "b", lty = 1, col='deeppink1')
lines(k_to_try, err_k_aldex, type = "b", lty = 1, col='orange2')
lines(k_to_try, err_k_clr, type = "b", lty = 1, col='black')

legend("bottomright", 
  legend = c('Raw','DESeq2', 'EdgeR','Aldex2', 'CLR'),
  col = c('darkolivegreen4','firebrick1', 'deeppink1', 'orange2', 'black'),
  pch = c(20,20,20,20,20), 
  text.col = "black",
  cex = 0.50)


plot(err_k_raw, type = "b", col = "darkolivegreen4",
     lty = 1, xlab = "k, number of neighbors", ylab = "Accuracy",
     main = "Accuracy with k-neighbors with raw data",ylim=c(60,103))

plot(err_k_deseq, type = "b", col = "darkolivegreen4",
     lty = 1, xlab = "k, number of neighbors", ylab = "Accuracy",
     main = "Accuracy with k-neighbors with DESeq2",ylim=c(60,103))

plot(err_k_aldex, type = "b", col = "darkolivegreen4",
     lty = 1, xlab = "k, number of neighbors", ylab = "Accuracy",
     main = "Accuracy with k-neighbors with ALDEx2",ylim=c(60,103))

plot(err_k_edge, type = "b", col = "darkolivegreen4",
     lty = 1, xlab = "k, number of neighbors", ylab = "Accuracy",
     main = "Accuracy with k-neighbors with Edge R",ylim=c(60,103))

plot(err_k_clr, type = "b", col = "darkolivegreen4",
     lty = 1, xlab = "k, number of neighbors", ylab = "Accuracy",
     main = "Accuracy with k-neighbors with CLR",ylim=c(60,103))

```


```{r}

```
